// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menuitem-tag-selected'
  | 'notice-no-items-selected'
  | 'notice-tagging-done'
  | 'notice-tagging-progress'
  | 'notice-tagging-start'
  | 'pref-apikey-label'
  | 'pref-browse'
  | 'pref-help'
  | 'pref-python-label'
  | 'pref-script-label'
  | 'pref-strictness-label'
  | 'pref-strictness-lax'
  | 'pref-strictness-strict'
  | 'pref-synonyms-label'
  | 'pref-title'
  | 'pref-watcher-enabled'
  | 'startup-begin'
  | 'startup-finish';
