// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "watcherEnabled": boolean;
      "apiKey": string;
      "strictness": number;
      "synonymFile": string;
      "pythonPath": string;
      "scriptPath": string;
    };
  }
}
